const operations = Object.freeze({
    CREATEUSER: 'CREATEUSER',
    DELETEFILE: 'DELETEFILE',
    ADDFILE: 'ADDFILE',
    ADDMINIOSERVER: 'ADDMINIOSERVER',
    ADDCLUSTER: 'ADDCLUSTER',
    MARK_NON_REACHABLE_SERVER: 'MARK_NON_REACHABLE_SERVER'
});

module.exports = {
    operations
}